#ifndef _KIPR_CONFIG_H_
#define _KIPR_CONFIG_H_

#define KIPR_MODULE_ACCEL
#define KIPR_MODULE_ANALOG
#define KIPR_MODULE_AUDIO
#define KIPR_MODULE_BATTERY
#define KIPR_MODULE_BOTBALL
#define KIPR_MODULE_BUTTON
#define KIPR_MODULE_CAMERA
#define KIPR_MODULE_COMPASS
#define KIPR_MODULE_CONSOLE
#define KIPR_MODULE_CREATE
#define KIPR_MODULE_DIGITAL
#define KIPR_MODULE_GRAPHICS
#define KIPR_MODULE_GYRO
#define KIPR_MODULE_MAGNETO
#define KIPR_MODULE_MOTOR
#define KIPR_MODULE_SERVO
#define KIPR_MODULE_THREAD
#define KIPR_MODULE_TIME
#endif
